# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание 1

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [8]:
# ваш код здесь
a@a.T

array([[1.57995312, 0.48673782, 1.28525324, 0.9947397 , 0.64675177],
       [0.48673782, 0.40706809, 0.26368252, 0.57840584, 0.55984141],
       [1.28525324, 0.26368252, 1.11497408, 0.64198458, 0.34157207],
       [0.9947397 , 0.57840584, 0.64198458, 1.44251562, 0.77015453],
       [0.64675177, 0.55984141, 0.34157207, 0.77015453, 0.77110897]])

In [9]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [10]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание 2

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [11]:
# ваш код здесь
numbers = np.arange(1, 10001)
(numbers ** 2).sum()

np.int64(333383335000)

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [15]:
x = torch.rand(5, 3)
x

tensor([[0.4074, 0.5447, 0.6875],
        [0.1727, 0.7130, 0.4088],
        [0.3356, 0.2658, 0.5648],
        [0.1521, 0.3240, 0.7814],
        [0.9991, 0.6071, 0.3986]])

In [16]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [17]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.4074, 5.5447, 5.6875],
        [5.1727, 5.7130, 5.4088],
        [5.3356, 5.2658, 5.5648],
        [5.1521, 5.3240, 5.7814],
        [5.9991, 5.6071, 5.3986]])



In [18]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[0.9353, 0.7398, 0.6698, 0.7756, 1.0117],
        [0.7398, 0.7054, 0.4784, 0.5767, 0.7684],
        [0.6698, 0.4784, 0.5023, 0.5785, 0.7218],
        [0.7756, 0.5767, 0.5785, 0.7386, 0.6601],
        [1.0117, 0.7684, 0.7218, 0.6601, 1.5257]])

X*X^T  (2):
tensor([[0.9353, 0.7398, 0.6698, 0.7756, 1.0117],
        [0.7398, 0.7054, 0.4784, 0.5767, 0.7684],
        [0.6698, 0.4784, 0.5023, 0.5785, 0.7218],
        [0.7756, 0.5767, 0.5785, 0.7386, 0.6601],
        [1.0117, 0.7684, 0.7218, 0.6601, 1.5257]])



In [19]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.5465, 0.4315, 0.3887, 0.4191, 0.6683])



In [20]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [21]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-21-2248688129>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [ ]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 5.6767e+10,  3.1742e-41,  5.4992e+09],
        [ 3.1742e-41, -2.3862e-25,  4.5448e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [ ]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.3190, 0.8694, 0.9860],
        [0.7349, 0.9223, 0.6015],
        [0.5761, 0.0790, 0.7863],
        [0.2975, 0.6295, 0.0814],
        [0.3029, 0.8073, 0.5870]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [ ]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 0.3286, -0.7028, -1.0239],
        [-3.2129, -0.3765, -0.8188],
        [-0.7487,  1.7554, -0.3971],
        [-0.5781,  0.8157,  0.5225],
        [ 1.3523,  0.1054,  0.6236]]) torch.Size([5, 3])


## Задание 3

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [26]:
import torch

torch.manual_seed(42)

# ваш код здесь
x = torch.rand(5, 3)
y = torch.rand(5, 3)

(x+y)[0][0]

tensor(1.3117)

In [24]:
print(x * y) # поэлементное умножение

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])


## Задание 4

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [27]:
# your code here
(x@y.T)[-1][-1]

tensor(0.4885)

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
# b @ a